export const Info = [
  {
    id: "0",
    row: 0,
    col: 0,
    w: 1,
    h: 1,
    name: "Hugo Hernandez Figueroa",
    filter: ["Principal Investigator", "All"],
    src: "/hugo.jfif",
    charge: "Head of the DECOM-UNICAMP",
    career: "Professor of Electrical Engineering",
    email: "hugo@unicamp.br",
    link: "https://scholar.google.com/citations?user=kA9oak0AAAAJ&hl=en&oi=sra",
    content: [
      "Hugo E. Hernández Figueroa received the B.Sc. degree in electrical engineering from the Federal University of Rio Grande do Sul, Porto Alegre, Brazil, in 1983.",
      "He received the M.Sc. degree in electrical engineering and the M.Sc. in informatics, from the Pontifical Catholic University of Rio de Janeiro, Rio de Janeiro, Brazil, in 1985 and 1987, respectively, and the Ph.D. degree in physics from the Imperial College of Science, Technology and Medicine, London, UK, in 1992.",
      "After spending two years as a Postdoctoral Fellow with the Department of Electronic and Electrical Engineering, UCL, London, UK, he joined the UNICAMP, FEEC, as an Assistant Professor in 1995.",
      "He became Full Professor in 2005. He has been an Associate Editor (Nanophotonics) of the IEEE Photonics Journal since March 2011, and was an Associate Editor (Opto-Electronics/Integrated Optics) of the IEEE/OSA Journal of Lightwave Technology (January 2004 – December 2009).",
      "He is a Fellow of the OSA class 2011, was a recipient of the IEEE Third Millennium Medal in 2000, and also, the recipient of the Attilio Giarola’s Medal in 2013, for outstanding research achievements from the SBMO. He has acted as area coordinator of engineering at the Brazilian Agency FAPESP since 2014.",
      "Presently he is the Director of the National Institute of Science and Technology FOTONICOM. His main research topics are: integrated photonics, optical fibers, antennas, microwaves, and computational electromagnetics, applied to telecommunications and biosensing.",
    ],
  },
  {
    id: "1",
    row: 0,
    col: 1,
    w: 1,
    h: 1,
    name: "Gianni Masaki Tanaka Portela",
    filter: ["Post Doctoral Fellow", "All"],
    src: "/gianni.jpg",
  },
  {
    id: "2",
    row: 0,
    col: 2,
    w: 1,
    h: 1,
    name: "Luciano Prado de Oliveira",
    filter: ["Senior Research Scientist", "All"],
  },
  {
    id: "3",
    row: 0,
    col: 3,
    w: 1,
    h: 1,
    name: "Luz Ariovaldo Fabri Junior",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "4",
    row: 1,
    col: 0,
    w: 1,
    h: 1,
    name: "Adriano da Silva Ferreira",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "5",
    row: 1,
    col: 1,
    w: 1,
    h: 1,
    name: "Yesica Raquel Rumaldo Bustamente",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "6",
    row: 1,
    col: 2,
    w: 1,
    h: 1,
    name: "Gilliard Nardel Malheiros Silveira",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "7",
    row: 1,
    col: 3,
    w: 1,
    h: 1,
    name: "José Angel Borda Hernández",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "8",
    row: 2,
    col: 0,
    w: 1,
    h: 1,
    name: "Juan Pablo Pantoja Bastidas",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "9",
    row: 2,
    col: 1,
    w: 1,
    h: 1,
    name: "Valquíria Lima Bessa de Castro",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "10",
    row: 2,
    col: 2,
    w: 1,
    h: 1,
    name: "Felício Harley Garcia de Castro",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "11",
    row: 2,
    col: 3,
    w: 1,
    h: 1,
    name: "Juliana de Almeida Góes",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "12",
    row: 3,
    col: 0,
    w: 1,
    h: 1,
    name: "Tadeu Pires Pasetto",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "13",
    row: 3,
    col: 1,
    w: 1,
    h: 1,
    name: "Ursula Fernanda Salazar Roggero",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "14",
    row: 3,
    col: 2,
    w: 1,
    h: 1,
    name: "Yuri Hayashi Isayama",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "15",
    row: 3,
    col: 3,
    w: 1,
    h: 1,
    name: "Jorge Rufino Fernández Herrera",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "16",
    row: 4,
    col: 0,
    w: 1,
    h: 1,
    name: "Francisco Teixeira Orlandini",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "17",
    row: 4,
    col: 1,
    w: 1,
    h: 1,
    name: "Marlon de Souza Alcântara",
    filter: ["Graduate Student MSc", "All"],
  },
  {
    id: "18",
    row: 4,
    col: 2,
    w: 1,
    h: 1,
    name: "Gian Carlos Oré Huacles",
    filter: ["Graduate Student MSc", "All"],
  },
  {
    id: "19",
    row: 4,
    col: 3,
    w: 1,
    h: 1,
    name: "Rafaela Silveira Cardoso",
    filter: ["Graduate Student MSc", "All"],
  },
  {
    id: "20",
    row: 5,
    col: 0,
    w: 1,
    h: 1,
    name: "Vitor de Oliveira Freire",
    filter: ["Undergrad ", "All"],
  },
  {
    id: "21",
    row: 5,
    col: 1,
    w: 1,
    h: 1,
    name: "Michel Zamboni Rached",
    filter: ["Faculty Member", "All"],
  },
  {
    id: "22",
    row: 5,
    col: 2,
    w: 1,
    h: 1,
    name: "Lucas Heitzmann Gabriell",
    filter: ["Faculty Member", "All"],
  },
];
