export const Info = [
  {
    id: '1',
    row: 0,
    col: 0,
    w: 1,
    h: 1,
    name: 'Luciano Prado de Oliveira',
    filter: ['Pesq Colab', 'All'],
  },
  {
    id: '2',
    row: 0,
    col: 1,
    w: 1,
    h: 1,
    name: 'Gianni Masaki Tanaka Portela',
    filter: ['PD', 'All'],
  },
  {
    id: '3',
    row: 0,
    col: 2,
    w: 1,
    h: 1,
    name: 'Luz Ariovaldo Fabri Junior',
    filter: ['Pesq Assoc', 'All'],
  },
  {
    id: '4',
    row: 0,
    col: 3,
    w: 1,
    h: 1,
    name: 'Adriano da Silva Ferreira',
    filter: ['Pesq Assoc', 'All'],
  },
  {
    id: '5',
    row: 1,
    col: 0,
    w: 1,
    h: 1,
    name: 'Yesica Raquel Rumaldo Bustamente',
    filter: ['Pesq Assoc', 'All'],
  },
  {
    id: '6',
    row: 1,
    col: 1,
    w: 1,
    h: 1,
    name: 'Gilliard Nardel Malheiros Silveira',
    filter: ['Pesq Assoc', 'All'],
  },
  {
    id: '7',
    row: 1,
    col: 2,
    w: 1,
    h: 1,
    name: 'José Angel Borda Hernández',
    filter: ['Phd', 'All'],
  },
  {
    id: '8',
    row: 1,
    col: 3,
    w: 1,
    h: 1,
    name: 'Juan Pablo Pantoja Bastidas',
    filter: ['Phd', 'All'],
  },
  {
    id: '9',
    row: 2,
    col: 0,
    w: 1,
    h: 1,
    name: 'Valquíria Lima Bessa de Castro',
    filter: ['Phd', 'All'],
  },
  {
    id: '10',
    row: 2,
    col: 1,
    w: 1,
    h: 1,
    name: 'Felício Harley Garcia de Castro',
    filter: ['Phd', 'All'],
  },
  {
    id: '11',
    row: 2,
    col: 2,
    w: 1,
    h: 1,
    name: 'Juliana de Almeida Góes',
    filter: ['Phd', 'All'],
  },
  {
    id: '12',
    row: 2,
    col: 3,
    w: 1,
    h: 1,
    name: 'Tadeu Pires Pasetto',
    filter: ['Phd', 'All'],
  },
  {
    id: '13',
    row: 3,
    col: 0,
    w: 1,
    h: 1,
    name: 'Ursula Fernanda Salazar Roggero',
    filter: ['Phd', 'All'],
  },
  {
    id: '14',
    row: 3,
    col: 1,
    w: 1,
    h: 1,
    name: 'Yuri Hayashi Isayama',
    filter: ['Phd', 'All'],
  },
  {
    id: '15',
    row: 3,
    col: 2,
    w: 1,
    h: 1,
    name: 'Jorge Rufino Fernández Herrera',
    filter: ['Phd', 'All'],
  },
  {
    id: '16',
    row: 3,
    col: 3,
    w: 1,
    h: 1,
    name: 'Francisco Teixeira Orlandini',
    filter: ['Phd', 'All'],
  },
  {
    id: '17',
    row: 4,
    col: 0,
    w: 1,
    h: 1,
    name: 'Marlon de Souza Alcântara',
    filter: ['Master', 'All'],
  },
  {
    id: '18',
    row: 4,
    col: 1,
    w: 1,
    h: 1,
    name: 'Gian Carlos Oré Huacles',
    filter: ['Master', 'All'],
  },
  {
    id: '19',
    row: 4,
    col: 2,
    w: 1,
    h: 1,
    name: 'Rafaela Silveira Cardoso',
    filter: ['Master', 'All'],
  },
  {
    id: '20',
    row: 4,
    col: 3,
    w: 1,
    h: 1,
    name: 'Vitor de Oliveira Freire',
    filter: ['IC', 'All'],
  },
];
