export const Info = [
  {
    id: "0",
    row: 0,
    col: 0,
    w: 1,
    h: 1,
    name: "Hugo Hernandez Figueroa",
    filter: ["Principal Investigator", "All"],
    src: "/hugo.jfif",
  },
  {
    id: "1",
    row: 0,
    col: 1,
    w: 1,
    h: 1,
    name: "Gianni Masaki Tanaka Portela",
    filter: ["Post Doctoral Fellow", "All"],
    src: "/gianni.jpg",
  },
  {
    id: "2",
    row: 0,
    col: 2,
    w: 1,
    h: 1,
    name: "Luciano Prado de Oliveira",
    filter: ["Senior Research Scientist", "All"],
  },
  {
    id: "3",
    row: 0,
    col: 3,
    w: 1,
    h: 1,
    name: "Luz Ariovaldo Fabri Junior",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "4",
    row: 1,
    col: 0,
    w: 1,
    h: 1,
    name: "Adriano da Silva Ferreira",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "5",
    row: 1,
    col: 1,
    w: 1,
    h: 1,
    name: "Yesica Raquel Rumaldo Bustamente",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "6",
    row: 1,
    col: 2,
    w: 1,
    h: 1,
    name: "Gilliard Nardel Malheiros Silveira",
    filter: ["Associate Research Scientist", "All"],
  },
  {
    id: "7",
    row: 1,
    col: 3,
    w: 1,
    h: 1,
    name: "José Angel Borda Hernández",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "8",
    row: 2,
    col: 0,
    w: 1,
    h: 1,
    name: "Juan Pablo Pantoja Bastidas",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "9",
    row: 2,
    col: 1,
    w: 1,
    h: 1,
    name: "Valquíria Lima Bessa de Castro",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "10",
    row: 2,
    col: 2,
    w: 1,
    h: 1,
    name: "Felício Harley Garcia de Castro",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "11",
    row: 2,
    col: 3,
    w: 1,
    h: 1,
    name: "Juliana de Almeida Góes",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "12",
    row: 3,
    col: 0,
    w: 1,
    h: 1,
    name: "Tadeu Pires Pasetto",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "13",
    row: 3,
    col: 1,
    w: 1,
    h: 1,
    name: "Ursula Fernanda Salazar Roggero",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "14",
    row: 3,
    col: 2,
    w: 1,
    h: 1,
    name: "Yuri Hayashi Isayama",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "15",
    row: 3,
    col: 3,
    w: 1,
    h: 1,
    name: "Jorge Rufino Fernández Herrera",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "16",
    row: 4,
    col: 0,
    w: 1,
    h: 1,
    name: "Francisco Teixeira Orlandini",
    filter: ["Graduate Student PhD", "All"],
  },
  {
    id: "17",
    row: 4,
    col: 1,
    w: 1,
    h: 1,
    name: "Marlon de Souza Alcântara",
    filter: ["Graduate Student MSc", "All"],
  },
  {
    id: "18",
    row: 4,
    col: 2,
    w: 1,
    h: 1,
    name: "Gian Carlos Oré Huacles",
    filter: ["Graduate Student MSc", "All"],
  },
  {
    id: "19",
    row: 4,
    col: 3,
    w: 1,
    h: 1,
    name: "Rafaela Silveira Cardoso",
    filter: ["Graduate Student MSc", "All"],
  },
  {
    id: "20",
    row: 5,
    col: 0,
    w: 1,
    h: 1,
    name: "Vitor de Oliveira Freire",
    filter: ["Undergrad ", "All"],
  },
];
